name: geSuitBans
main : net.cubespace.geSuitBans.geSuitBans
version: ${project.version}b-${build.number}
description: Part of the geSuit this plugin allows moderators to ban and kick players
author: geNAZt
commands:
    ban:
        description: Bans a player from the proxy
        aliases: [banplayer]
        permission: gesuit.bans.command.ban
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command> (player)
               /<command> (player) (message)
    checkban:
        description: Gets info about a players ban
        aliases: [lookupban,baninfo]
        permission: gesuit.bans.command.checkban
        permission-message: §cYou do not have permission for this command
        usage: /<command>  (player)
    banhistory:
        description: Gets the ban history of a player
        aliases: [bhistory]
        permission: gesuit.bans.command.banhistory
        permission-message: §cYou do not have permission for this command
        usage: /<command>  (player)
    ipban:
        description: Bans an IP from the proxy
        aliases: [banip]
        permission: gesuit.bans.command.ipban
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command>  (player)
               /<command> (ip)
               /<command> (ip/player) (message)
    kick:
        description: Kick a player from the proxy
        aliases: [kickplayer, playerkick, kickp,pkick]
        permission: gesuit.bans.command.kick
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command>  (player)
               /<command> (player) (message)
    kickall:
        description: Kicks everyone from the proxy
        aliases: [kicka]
        permission: gesuit.bans.command.kickall
        permission-message: §cYou do not have permission for this command
        usage: |
               /<command>
               /<command>  (message)
    reloadbans:
        description: Reloads the bans config
        aliases: [bansreload, reloadban, banreload]
        permission: gesuit.bans.command.reload
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    tempban:
        description: Temporarily bans a player from the proxy
        aliases: [tban, bant, bantemp]
        permission: gesuit.bans.command.tempban
        permission-message: §cYou do not have permission for this command
        usage: |
               "/<command> (player) (time) (reason)"
               "/<command> (player) (time) (reason)"        
               "Exemple of a (time): 2d5h"        
    unban:
        description: Unbans a player from the proxy
        aliases: [uban, removeban, pardon]
        permission: gesuit.bans.command.ban
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    unipban:
        description: Unbans an IP from the proxy
        aliases: [ipunban, unbanip, ipsafe, safeip]
        permission: gesuit.bans.command.ipban
        permission-message: §cYou do not have permission for this command
        usage: /<command> (ip)

permissions:
    gesuit.bans.*:
        description: Gives access to all bans commands
        default: op
        children:
            gesuit.chat.admin: true
    gesuit.bans.admin:
        description: Gives access to all bans admin commands
        children:
            gesuit.bans.command.kickall: true
            gesuit.bans.command.ipban: true
            gesuit.bans.command.reload: true
            gesuit.bans.mod: true
    gesuit.bans.mod:
        description: Gives access to all bans mod commands
        children:
            gesuit.bans.command.ban: true
            gesuit.bans.command.checkban: true
            gesuit.bans.command.banhistory: true
            gesuit.bans.command.kick: true
            gesuit.bans.command.tempban: true
        

        